FROM node:lts-alpine

RUN apk add --update --no-cache vim

WORKDIR /home/node/app

COPY --chown=node:node package.json /home/node/app/

RUN npm install -g @adonisjs/cli && npm install && \
    chown -R node:node node_modules/

COPY --chown=node:node . /home/node/app/

RUN chmod +x wait-for.sh

EXPOSE 3333

USER node
CMD sh -c './wait-for.sh rubiks-mysql:3306 -- adonis migration:run && npm run start-dev'