FROM node:lts-alpine

RUN apk add --update --no-cache vim

WORKDIR /home/node/app

COPY package.json /home/node/app/
RUN npm install -g @adonisjs/cli && npm install
COPY . /home/node/app/

RUN chmod +x ./wait-for.sh

EXPOSE 3333

USER node
CMD sh -c './wait-for.sh rubiks-mysql:3306 -- adonis migration:run && npm run start-dev'